### Deep Learning - ANN Project

In [3]:
import sys
print(sys.executable)

c:\Users\USER\anaconda3\python.exe


In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import tensorflow as tf
from tensorflow import keras
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

In [2]:
df = pd.read_csv("Potato_Price_Prediction_Data.csv")
df.head()

,potato_kg,potato_price
0,1,20
1,2,38
2,3,56
3,4,74
4,5,92


In [3]:
df.shape

(200, 2)

In [4]:
X = df[['potato_kg']] # dataframe (2D)
Y = df['potato_price'] # series (1D)

In [5]:
# Scale the data (THIS FIXES THE NaN ISSUE)
scaler_X = MinMaxScaler()
scaler_Y = MinMaxScaler()
X = scaler_X.fit_transform(X)
Y = scaler_Y.fit_transform(Y.values.reshape(-1, 1))

### Split Dataset fro Train and Test

In [7]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2) # 20% for test. so 80% for training

### ANN Model Building
- Dense(1) → One neuron in the output layer
- input_shape=[1] → Expects 1 input feature (potato_kg)
- activation='linear' → Output = input × weight + bias 
- The model will find the best weight (slope) and bias (intercept) during training

- This is a straight line model: y = mx + b where x = potato_kg and y = predicted price.

In [8]:
X_test

array([[0.68844221],
       [0.27135678],
       [0.78894472],
       [0.73366834],
       [0.74371859],
       [0.42713568],
       [0.52763819],
       [0.94974874],
       [0.55276382],
       [0.61809045],
       [0.36683417],
       [0.2361809 ],
       [0.57286432],
       [0.18090452],
       [0.48241206],
       [0.96482412],
       [0.1959799 ],
       [0.57788945],
       [0.59798995],
       [0.6080402 ],
       [0.95979899],
       [0.37688442],
       [0.1758794 ],
       [0.97487437],
       [0.72361809],
       [0.98994975],
       [0.34673367],
       [0.22110553],
       [0.99497487],
       [0.47738693],
       [0.10552764],
       [0.3919598 ],
       [0.11557789],
       [0.64321608],
       [0.03015075],
       [0.11055276],
       [0.24120603],
       [0.12562814],
       [0.33165829],
       [0.53266332]])

In [9]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(1, input_shape=[1], activation='linear')
])

c:\python\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


### Compile The ANN Model

- optimizer='sgd':
SGD = Stochastic Gradient Descent
Controls how the model learns (updates weights)
Works by taking small steps downhill to minimize the loss

- loss='mean_squared_error':
MSE = Average of (predicted - actual)²
Measures how wrong the model is
Lower = better predictions
Standard for regression problems (predicting continuous numbers like price)

In [10]:
model.compile(
    optimizer='sgd', 
    loss='mean_squared_error', 
    metrics=['mae'] # Mean Absolute Error
)

### Train Model

In [11]:
model.fit(X_train, Y_train, epochs=50)

Epoch 1/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 1.2329 - mae: 0.9517 
Epoch 2/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.9979 - mae: 0.8407
Epoch 3/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.8149 - mae: 0.7508 
Epoch 4/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.6734 - mae: 0.6772 
Epoch 5/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.5631 - mae: 0.6174 
Epoch 6/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.4775 - mae: 0.5691 
Epoch 7/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.4110 - mae: 0.5282 
Epoch 8/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.3584 - mae: 0.4948 
Epoch 9/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.3176 - mae: 0.4692 
Epoch 10/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.2853 - mae: 0.4477 
Epoch 11/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.2599 - mae: 0.4305 
Epoch 12/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.2397 - mae: 0.4161 
Epoch 13/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.2

### Prediction

In [12]:
model.predict(X_test)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step


array([[0.51790315],
       [0.56366056],
       [0.50687724],
       [0.5129415 ],
       [0.5118389 ],
       [0.5465704 ],
       [0.5355446 ],
       [0.48923582],
       [0.5327881 ],
       [0.52562124],
       [0.553186  ],
       [0.5675196 ],
       [0.5305829 ],
       [0.57358384],
       [0.5405062 ],
       [0.48758194],
       [0.57193   ],
       [0.5300316 ],
       [0.5278264 ],
       [0.52672386],
       [0.48813325],
       [0.5520834 ],
       [0.5741352 ],
       [0.48647934],
       [0.51404405],
       [0.48482546],
       [0.55539113],
       [0.5691735 ],
       [0.48427418],
       [0.54105747],
       [0.5818533 ],
       [0.5504295 ],
       [0.5807507 ],
       [0.52286476],
       [0.5901227 ],
       [0.581302  ],
       [0.5669683 ],
       [0.5796481 ],
       [0.55704504],
       [0.53499323]], dtype=float32)

In [13]:
X_test

array([[0.68844221],
       [0.27135678],
       [0.78894472],
       [0.73366834],
       [0.74371859],
       [0.42713568],
       [0.52763819],
       [0.94974874],
       [0.55276382],
       [0.61809045],
       [0.36683417],
       [0.2361809 ],
       [0.57286432],
       [0.18090452],
       [0.48241206],
       [0.96482412],
       [0.1959799 ],
       [0.57788945],
       [0.59798995],
       [0.6080402 ],
       [0.95979899],
       [0.37688442],
       [0.1758794 ],
       [0.97487437],
       [0.72361809],
       [0.98994975],
       [0.34673367],
       [0.22110553],
       [0.99497487],
       [0.47738693],
       [0.10552764],
       [0.3919598 ],
       [0.11557789],
       [0.64321608],
       [0.03015075],
       [0.11055276],
       [0.24120603],
       [0.12562814],
       [0.33165829],
       [0.53266332]])

In [14]:
input_scaled = scaler_X.transform([[24]])
prediction_scaled = model.predict(input_scaled)
prediction = scaler_Y.inverse_transform(prediction_scaled)
print(prediction[0][0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step
2100.249


c:\python\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
