## Basics of Numpy Library

In [1]:
import numpy as np

### Create Numpy Array

In [2]:
arr = np.array([1, 2, 3, 4, 5])
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[1 2 3 4 5]


### Create a Matrix

In [7]:
l = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] # list
arr = np.array(l)
print(arr)
print(type(arr)) # array
print(type(l)) # list

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
<class 'list'>


### Array Generation Function

np.arrange():

In [8]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

np.zeros():

In [11]:
arr = np.zeros(4)
arr

array([0., 0., 0., 0.])

In [13]:
arr = np.zeros( (4, 6) )
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

np.ones():

In [14]:
arr = np.ones( (4, 8) )
arr

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

np.linspace():  -> used to generate an array of evenly spaced numbers over a specified interval

In [15]:
arr = np.linspace(0, 1, 100)
arr

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

### Random Generation Function

In [16]:
np.random.rand(10)

array([0.20335031, 0.01326936, 0.39126798, 0.12047968, 0.24667646,
       0.98076475, 0.10922029, 0.55570621, 0.25811182, 0.89089372])

In [17]:
np.random.randn(10)

array([-0.65393671, -0.03947489,  0.37318381, -0.00225889, -0.21655928,
       -0.30303481, -1.23667683, -1.01158171, -0.3587552 ,  0.67244931])

In [ ]:
np.random.randint(10, 20, 10) # it return 10 random number 10 to 20

array([12, 11, 11, 16, 10, 14, 18, 14, 12, 12], dtype=int32)

### Array Attributes

In [22]:
arr = np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9],[10, 11, 12] ])
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
arr.shape  # return array shape

(4, 3)

In [ ]:
arr.size  # return how many elm

12

In [25]:
arr.dtype # type of array

dtype('int64')

### Array Methods

In [34]:
arr = np.array([ [10, -2, 23], [4, 15, 6], [77, 8, 9],[19, 11, 2] ])
arr

array([[10, -2, 23],
       [ 4, 15,  6],
       [77,  8,  9],
       [19, 11,  2]])

In [35]:
arr.min()

np.int64(-2)

In [37]:
arr.min().item()

-2

In [41]:
arr.max()

np.int64(77)

In [38]:
arr.max().item()

77

In [43]:
arr.sum()

np.int64(182)

In [ ]:
np.sum(arr, axis=0) # y-axis

array([110,  32,  40])

In [ ]:
np.sum(arr, axis=1) # x-axis

array([31, 25, 94, 32])

In [52]:
arr.mean()

np.float64(15.166666666666666)

In [53]:
# standard division
arr.std()

np.float64(19.810911695886745)

In [56]:
# max elm index no
arr.argmax()

np.int64(6)

In [57]:
# min elm index no
arr.argmin()

np.int64(1)

### Reshaping and Resizing

In [59]:
# taken a normal array to convert matrix shape

arr = np.arange(1, 31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [ ]:
arr.reshape(5, 7) # get err bcz here elm are 5*7= 35. But our array elm is 30

ValueError: cannot reshape array of size 30 into shape (5,7)

In [63]:
arr.reshape(5, 6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [64]:
resized_large = np.resize(arr, (35,)) 
resized_large

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30,  1,  2,  3,  4,
        5])

In [65]:
resized_small = np.resize(arr, (3,))
resized_small

array([1, 2, 3])

In [4]:
arr = np.arange(1, 31).reshape(5, 6)
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [6]:
arr[0:3, -5:-1]

array([[ 2,  3,  4,  5],
       [ 8,  9, 10, 11],
       [14, 15, 16, 17]])

In [7]:
n = 5
arr = np.zeros((n, n))
arr[n // 2, :] = 1
arr[ : , n // 2] = 1 
arr

array([[0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [1., 1., 1., 1., 1.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.]])