In [2]:
import numpy as np

### Numpy Indexing and Slicing of Vector

In [3]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[0].item()

1

In [6]:
arr[1:4]

array([2, 3, 4])

In [7]:
arr[4:]

array([ 5,  6,  7,  8,  9, 10])

In [8]:
arr[:5]

array([1, 2, 3, 4, 5])

In [9]:
arr[:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Numpy Indexing and Slicing of Matrix

In [14]:
arr = np.arange(1, 51).reshape(5, 10)
arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [15]:
arr[2] # 2 no ROW

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [ ]:
arr[:, 2] # 2 no col

array([ 3, 13, 23, 33, 43])

In [17]:
arr[2, 4].item() # 2 no row,4 no col

25

In [20]:
arr[1 : 3, 4 : 6]

array([[15, 16],
       [25, 26]])

In [24]:
arr[2: , 7:]

array([[28, 29, 30],
       [38, 39, 40],
       [48, 49, 50]])

### Boolean Indexing

In [3]:
arr = np.arange(1, 21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [28]:
# find even number
bool_idx = arr % 2 == 0
bool_idx

array([False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True])

In [29]:
new_arr = arr[bool_idx]
new_arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [7]:
# shortcut
arr[arr % 2 == 0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])