## NUMPY ARRAY OPERATIONS

In [3]:
import numpy as np

### Arithmetic Operations:

In [ ]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6,  7,  8,  9, 10])

array([1, 2, 3, 4, 5])

In [16]:
arr1 + arr2
arr2 - arr1
arr1 * arr2
arr1 / arr2
arr1 // arr2
arr1 ** arr2
arr1 ^ arr2

array([ 7,  5, 11, 13, 15])

In [30]:
# Operation on Matrix
arr1 = np.array( [[1, 2, 3], [4, 5, 6], [7, 8, 9]] )
arr2 = np.array( [[1, 2, 3], [4, 5, 6], [7, 8, 9]] )


In [32]:
arr1 + arr2
arr1 * arr2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

### BroadCasting:

In [19]:
l = [10, 20, 30, 40, 50]
arr = np.array(l)
arr + 10
arr * 10

array([100, 200, 300, 400, 500])

In [33]:
arr = np.array( [[1, 2, 3], [4, 5, 6], [7, 8, 9]] )
arr + 10

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

### Deep and Shallow Copy:

In [40]:
arr = np.arange(1, 21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [43]:
slice = arr[ : 5]
slice = slice * 10
slice

array([10, 20, 30, 40, 50])

In [44]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

Shallow Copy

In [50]:
import copy

list1 = [1, 2, [3, 4]]
list2 = copy.copy(list1)

list2[2][0] = 99  # This changes BOTH lists
print(list1)

[1, 2, [99, 4]]


Deep Copy

In [51]:
import copy
list1 = [1, 2, [3, 4]]
list2 = copy.deepcopy(list1)

list2[2][0] = 99  # This changes ONLY list2
print(list1) 

[1, 2, [3, 4]]


### Matrix Operations:

In [52]:
m1 = np.array([ [1, 2], [3, 4] ])
m2 = np.array([ [5, 6], [7, 8] ])

In [ ]:
# Normal Multiplication
m1 * m2

array([[19, 22],
       [43, 50]])

MATRIX Multiplication

In [ ]:
m1 = np.arange(1, 7).reshape(2, 3)
m1

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
m2 = np.arange(7, 13).reshape(3, 2)
m2

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [ ]:
m1 * m2 #  Normal Multiplication not applicable

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [ ]:
m1 @ m2 # MATRIX Multiplication

array([[ 58,  64],
       [139, 154]])

In [ ]:
# another way to write
np.dot(m1, m2)

array([[ 58,  64],
       [139, 154]])

Transpose Matrix 

In [63]:
m = np.array([ [1, 2, 3],[4, 5, 6] ])
m.T

array([[1, 4],
       [2, 5],
       [3, 6]])

### Advance Array Manipulation

Stacking Array

In [77]:
m1 = np.array([1, 2, 3, 4])
m1

array([1, 2, 3, 4])

In [78]:
m2 = np.array([5, 6, 7, 8])
m2

array([5, 6, 7, 8])

In [79]:
# Vertical stack
np.vstack((m1, m2))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [80]:
# Horizontal stack
np.hstack((m1, m2))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
# Column Stack
np.column_stack((m1, m2))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

Splitting Array

In [85]:
x = np.arange(1, 17).reshape(4, 4)
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [88]:
# Split into two parts
np.split(x, 2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [89]:
np.vsplit(x, 2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [90]:
np.hsplit(x, 2)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]