### Valid Sudoku

In [7]:
import numpy as np

In [8]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])
s

array([[5, 3, 4, 6, 7, 8, 9, 1, 2],
       [6, 7, 2, 1, 9, 5, 3, 4, 8],
       [1, 9, 8, 3, 4, 2, 5, 6, 7],
       [8, 5, 9, 7, 6, 1, 4, 2, 3],
       [4, 2, 6, 8, 5, 3, 7, 9, 1],
       [7, 1, 3, 9, 2, 4, 8, 5, 6],
       [9, 6, 1, 5, 3, 7, 2, 8, 4],
       [2, 8, 7, 4, 1, 9, 6, 3, 5],
       [3, 4, 5, 2, 8, 6, 1, 7, 9]])

In [9]:
x = np.sum(s, axis=1) # all row sum
x

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [26]:
for i in x:
    if(i != 45):
        print("This is not Valid Sudoku")
        break
print("This is valid sudoku for Row")

This is valid sudoku for Row


In [ ]:
y = np.sum(s, axis=0) # for col sum
y

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [ ]:
for i in y:
    if(i != 45):
        print("This is not Valid Sudoku")
print("This is valid sudoku for Columns")

This is valid sudoku for Cols


In [35]:
# for sub matrix
for i in range(0, 9, 3):

    for j in range(0, 9, 3):
        all_sub_matrix = s[i:i+3, j:j+3]
        print(all_sub_matrix.sum())

45
45
45
45
45
45
45
45
45


### General Questions

In [36]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [37]:
# Get the shape of the matrix.
data.shape

(5, 3)

In [47]:
# Find the average age of students.
x = data[: , 0]
sum = 0
for i in x:
    sum += i
avg = sum / len(x)
avg


np.float64(18.4)

In [ ]:
# using mean function
np.mean(data[: , 0])

np.float64(18.4)

In [50]:
# Find the highest Science mark.
arr = data[: , 2]
arr.max()

np.int64(95)

In [74]:
# Get details of the student who scored more than 90 in Math.
math_marks = data[: , 1] > 90
s = data[math_marks]

# Ensure s is always 2D
s = np.atleast_2d(s)

for i, st in enumerate(s, start=1):
    age, math, science = st
    print(f"Student {i}: Age {age}, Math {math}, Science {science}")

Student 1: Age 19, Math 92, Science 88


In [75]:
# Increase Math marks of all students by 5.
math_marks = data[: , 1] + 5
math_marks

array([90, 97, 81, 70, 95])

In [6]:
# find the 1st 3 rows with last 5 col

arr = np.arange(1, 31).reshape(5, 6)

arr[ :3, -5: ]

array([[ 2,  3,  4,  5,  6],
       [ 8,  9, 10, 11, 12],
       [14, 15, 16, 17, 18]])